/*
 * CitcomCU is a Finite Element Code that solves for thermochemical
 * convection within a three dimensional domain appropriate for convection
 * within the Earth's mantle. Cartesian and regional-spherical geometries
 * are implemented. See the file README contained with this distribution
 * for further details.
 * 
 * Copyright (C) 1994-2005 California Institute of Technology
 * Copyright (C) 2000-2005 The University of Colorado
 *
 * Authors: Louis Moresi, Shijie Zhong, and Michael Gurnis
 *
 * For questions or comments regarding this software, you may contact
 *
 *     Luis Armendariz <luis@geodynamics.org>
 *     http://geodynamics.org
 *     Computational Infrastructure for Geodynamics (CIG)
 *     California Institute of Technology
 *     2750 East Washington Blvd, Suite 210
 *     Pasadena, CA 91007
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 2 of the License, or any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */


/***********************************************************************
 *                                                                     *
 * WARNING: This file is auto-generated by the script `prototypes.py'. *
 *                                                                     *
 * Since the function prototypes can be generated, you should modify   *
 * the function definitions instead. You can then use the script to    *
 * keep the headers up to date.                                        *
 *                                                                     *
 * You can add (almost) anything you want in the section between the   *
 * BEGIN and END comments and it will be preserved.  Anything outside  *
 * those comments will be overwritten in the next pass.                *
 *                                                                     *
 * Ignore this warning if you will be maintaining this file manually   *
 * from now on.                                                        *
 *                                                                     *
 ***********************************************************************/


#ifndef __COMPOSITION_ADV_H__
#define __COMPOSITION_ADV_H__

/** BEGIN **/
#include "element_definitions.h"
#include "global_defs.h"
/** END **/

/* Composition_adv.c */
void Runge_Kutta(struct All_variables *E, float *C, float *V[4], int on_off);
void Euler(struct All_variables *E, float *C, float *V[4], int on_off);
void transfer_markers_processors(struct All_variables *E, int on_off);
void unify_markers_array(struct All_variables *E, int no_tran, int no_recv);
void prepare_transfer_arrays(struct All_variables *E);
int locate_processor(struct All_variables *E, double XMC1, double XMC2, double XMC3);
void get_C_from_markers(struct All_variables *E, float *C);
void element_markers(struct All_variables *E, int con);
void velocity_markers(struct All_variables *E, float *V[4], int con);
int get_element(struct All_variables *E, double XMC1, double XMC2, double XMC3, double dX[4]);
int in_the_domain(struct All_variables *E, double r, double t, double f);
float area_of_4node1(float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4);
float area_of_3node(float x1, float y1, float x2, float y2, float x3, float y3);
float mean_of_3node(int a, float x1, float y1, float x2, float y2, float x3, float y3);
float mean_of_4node(int a, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4);
float mean_of_5node(int a, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float x5, float y5);
float dist1(float XO[4], float XN[4]);

/* cproto command: /usr/bin/cproto -q -p -f 3 Composition_adv.c */
#endif
