/*
 * CitcomCU is a Finite Element Code that solves for thermochemical
 * convection within a three dimensional domain appropriate for convection
 * within the Earth's mantle. Cartesian and regional-spherical geometries
 * are implemented. See the file README contained with this distribution
 * for further details.
 * 
 * Copyright (C) 1994-2005 California Institute of Technology
 * Copyright (C) 2000-2005 The University of Colorado
 *
 * Authors: Louis Moresi, Shijie Zhong, and Michael Gurnis
 *
 * For questions or comments regarding this software, you may contact
 *
 *     Luis Armendariz <luis@geodynamics.org>
 *     http://geodynamics.org
 *     Computational Infrastructure for Geodynamics (CIG)
 *     California Institute of Technology
 *     2750 East Washington Blvd, Suite 210
 *     Pasadena, CA 91007
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 2 of the License, or any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */


/***********************************************************************
 *                                                                     *
 * WARNING: This file is auto-generated by the script `prototypes.py'. *
 *                                                                     *
 * Since the function prototypes can be generated, you should modify   *
 * the function definitions instead. You can then use the script to    *
 * keep the headers up to date.                                        *
 *                                                                     *
 * You can add (almost) anything you want in the section between the   *
 * BEGIN and END comments and it will be preserved.  Anything outside  *
 * those comments will be overwritten in the next pass.                *
 *                                                                     *
 * Ignore this warning if you will be maintaining this file manually   *
 * from now on.                                                        *
 *                                                                     *
 ***********************************************************************/


#ifndef __GLOBAL_OPERATIONS_H__
#define __GLOBAL_OPERATIONS_H__

/** BEGIN **/
#include "element_definitions.h"
#include "global_defs.h"
/** END **/

/* Global_operations.c */
void remove_horiz_ave(struct All_variables *E, float *X, float *H, int store_or_not);
void return_horiz_sum(struct All_variables *E, float *X, float *H, int nn);
void return_horiz_ave(struct All_variables *E, float *X, float *H);
float return_bulk_value(struct All_variables *E, float *Z, float z_thld, int average);
double global_vdot(struct All_variables *E, double *A, double *B, int lev);
double global_pdot(struct All_variables *E, double *A, double *B, int lev);
float global_tdot(struct All_variables *E, float *A, float *B, int lev);
float Tmax(struct All_variables *E, float *T);
float global_fmin(struct All_variables *E, float a);
float global_fmax(struct All_variables *E, float a);
void sum_across_depth_sph1(struct All_variables *E, float *sphc, float *sphs);
void sum_across_surface(struct All_variables *E, float *data, int total);
void sum_across_surf_sph1(struct All_variables *E, float *sphc, float *sphs);
void gather_TG_to_me0(struct All_variables *E, float *TG);
void propogator_down_process(struct All_variables *E, float *Tadi);
double sum_across_depth(struct All_variables *E, double temp1);

/* cproto command: /usr/bin/cproto -q -p -f 3 Global_operations.c */
#endif
