/*
 * CitcomCU is a Finite Element Code that solves for thermochemical
 * convection within a three dimensional domain appropriate for convection
 * within the Earth's mantle. Cartesian and regional-spherical geometries
 * are implemented. See the file README contained with this distribution
 * for further details.
 * 
 * Copyright (C) 1994-2005 California Institute of Technology
 * Copyright (C) 2000-2005 The University of Colorado
 *
 * Authors: Louis Moresi, Shijie Zhong, and Michael Gurnis
 *
 * For questions or comments regarding this software, you may contact
 *
 *     Luis Armendariz <luis@geodynamics.org>
 *     http://geodynamics.org
 *     Computational Infrastructure for Geodynamics (CIG)
 *     California Institute of Technology
 *     2750 East Washington Blvd, Suite 210
 *     Pasadena, CA 91007
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 2 of the License, or any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */


/***********************************************************************
 *                                                                     *
 * WARNING: This file is auto-generated by the script `prototypes.py'. *
 *                                                                     *
 * Since the function prototypes can be generated, you should modify   *
 * the function definitions instead. You can then use the script to    *
 * keep the headers up to date.                                        *
 *                                                                     *
 * You can add (almost) anything you want in the section between the   *
 * BEGIN and END comments and it will be preserved.  Anything outside  *
 * those comments will be overwritten in the next pass.                *
 *                                                                     *
 * Ignore this warning if you will be maintaining this file manually   *
 * from now on.                                                        *
 *                                                                     *
 ***********************************************************************/


#ifndef __VISCOSITY_STRUCTURES_H__
#define __VISCOSITY_STRUCTURES_H__

/** BEGIN **/
#include "element_definitions.h"
#include "global_defs.h"
/** END **/

/* Viscosity_structures.c */
void viscosity_parameters(struct All_variables *E);
void get_viscosity_option(struct All_variables *E);
void viscosity_for_system(struct All_variables *E);
void get_system_viscosity(struct All_variables *E, int propogate, float *evisc, float *visc);
void apply_viscosity_smoother(struct All_variables *E, float *visc, float *evisc);
void visc_from_mat(struct All_variables *E, float *Eta, float *EEta);
void visc_from_T(struct All_variables *E, float *Eta, float *EEta, int propogate);
void visc_from_S(struct All_variables *E, float *Eta, float *EEta, int propogate);
void strain_rate_2_inv(struct All_variables *E, float *EEDOT, int SQRT);
int layers(struct All_variables *E, float x3);
int weak_zones(struct All_variables *E, int node, float t_b);
float boundary_thickness(struct All_variables *E, float *H);

/* cproto command: /usr/bin/cproto -q -p -f 3 Viscosity_structures.c */
#endif
